services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: LugenStoreDb
      POSTGRES_PASSWORD: momo123
      POSTGRES_DB: LugenStoreDb
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: